### ISSUE TITLE
Make the repository use the storage PID

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1024]
Basically, stop using the `StoragePageAgnosticTrait` and drop it.

Also document that the storage PID needs to be set for the list view to work.

`TeaRepository::findByOwnerUid` needs to be adapted to ignore the storage PID (as it should find records from all pages).

**Comment by Starkmann** [comment]
Storage pid is set via TS and already part of the existing fixutre

**Comment by Starkmann** [comment]
findAllWithRecordsFindsRecordsFromAllPages this Test does not make scene any more, but  im not sure how/if we want to test if storage pid is respected if set.
