### ISSUE TITLE
PHP 8.3 builds fail on GitLab

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1034]
https://git.typo3.org/qa/example-extension/-/jobs/2782686

> Using Docker executor with image php:8.3 ...
> Pulling docker image php:8.3 ...
> WARNING: Failed to pull image with policy "always": Error response from daemon: manifest for php:8.3 not found: manifest unknown: manifest unknown (manager.go:250:1s)

**Comment by lukaszuznanski** [comment]
That was just test, that's not on main branch. There is no docker image which is called 8.3.

**Comment by lukaszuznanski** [comment]
I'm closing this one for now.
