### ISSUE TITLE
The JSON lint Composer script is suspiciously slow

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1046]
We should check if the script maybe scans too many files (e.g., 3rd-party Composer or Yarn packages).

**Comment by lukaszuznanski** [comment]
Looks like it's correct, here is output of find function which is used in json lint
```
 find . ! -path '*.Build/*' ! -path '*node_modules/*' -name '*.json'
./package.json
./composer.json
./.eslintrc.json
```

**Comment by oliverklee** [comment]
After running

```bash
./Build/Scripts/runTests.sh -s composer update --with-dependencies
```

I have a `.cache` directory that also contains lots of JSON files. So we'll need to exclude `.cache` from the JSON linting as well.
