### ISSUE TITLE
Allow installations with Symfony 7

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1113]
## Goal
I as a user would like to install Symfony 7 packages
## Acceptance Criteria

- [ ] Symfony 7 packages can be installed

## Additional Information
The TYPO3 Core now allows Symfony 7 on 12LTS and main: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82304

**Comment by deltanart** [comment]
When trying to install the symfony 7 packages I get this error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires typo3/coding-standards ^0.6.1 -> satisfiable by typo3/coding-standards[v0.6.1].
    - typo3/coding-standards v0.6.1 requires symfony/console ^4.4.30 || ^5.3.7 || ^6.0 -> found symfony/console[v4.4.30, ..., v4.4.49, v5.3.7, ..., v5.4.39, v6.0.0, ..., v6.4.7] but it conflicts with your root composer.json require (^7.0).
```

**Comment by DanielSiepmann** [comment]
I've added the issue to our next team call in order to discuss and solve the situation.

Thanks for investigating.

**Comment by DanielSiepmann** [comment]
There should now be an 0.8.0 release of the CGL package, thanks @oliverklee : https://github.com/TYPO3/coding-standards/issues/125#issuecomment-2145325791
