### ISSUE TITLE
Unblock argument passing in `Build/Scripts/runTests.sh`

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1149]
## Goal
I as a user want to pass the arguments directly to the command

## Acceptance Criteria

- [ ] the arguments are passing directly to the command
- [ ] the `-e`option is still there, but at the end of the script it shows a Deprecation Message

## Additional Information
https://review.typo3.org/c/Packages/TYPO3.CMS/+/82728

**Comment by DanielSiepmann** [comment]
This issue is superseeded by #1345 which will totaly remove the entries.
