### ISSUE TITLE
Align the Composer dispatcher in `runTests.sh` with the latest Core changes

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1157]
## Goal
I as a user want to align the composer dispatcher in `runTests.sh` with the latest Core changes.
## Acceptance Criteria

- [ ] the composer dispatcher is implemented
- [ ] composer commands are running fine

## Additional Information
This change adds a composer command dispatcher to `Build/Scripts/runTests.sh` to allow the execution of any composer command without the hassle to have a proper composer installed on the host system.
https://review.typo3.org/c/Packages/TYPO3.CMS/+/82787

**Comment by DanielSiepmann** [comment]
This was already solved with #899 and commit 00ba733b0e56675af573a6d684332d7d6f0857e7
