### ISSUE TITLE
Use correct command dispatch in `runTests.sh`

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1167]
## Goal
I as a user would like to use the correct command dispatch in `runTests.sh`
## Acceptance Criteria

- [x] the correct command is implemented
- [x] the command runs correct

## Additional Information
https://review.typo3.org/c/Packages/TYPO3.CMS/+/82934

**Comment by DanielSiepmann** [comment]
We already have that versions since commit 00ba733b0e56675af573a6d684332d7d6f0857e7 solved by #899
