### ISSUE TITLE
Migrate Services.yaml to Services.php

### ISSUE THREAD

**Issue by lukaszuznanski** [FriendsOfTYPO3/tea#1172]
Following best practices, migrate from .yaml to .php file

**Comment by DanielSiepmann** [comment]
I'd wait for https://notes.typo3.org/JKT4Cr6tSZehjq0Nu8o65g?both#decision-and-to-dos-separate-concepts-from-implementation-details-daniel before migrating. We should document that DI is best practice and why we use `Services.php` over `Services.yaml`. What are pros- and cons of both ways.
