### ISSUE TITLE
Apply some `runTests.sh` cleanup

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1195]
https://review.typo3.org/c/Packages/TYPO3.CMS/+/83515/2/Build/Scripts/runTests.sh

**Comment by sbuerk** [comment]
@oliverklee 

This issue can be closed, because the changes of the
linked TYPO3 core change has been already implemented
along with #1285 - except the acceptance test part,
which this extension does not have yet.
