### ISSUE TITLE
Change test string in setDescriptionSetsDescription()

### ISSUE THREAD

**Issue by schi** [FriendsOfTYPO3/tea#1204]
When writing the tests (copy/paste), there is a risk that not all functions will be properly adapted. 

Example:
If I derive setDescriptionSetsDescription() from a copy of setTitleSetsTitle() and do not adapt self::assertSame($value, $this->subject->getTitle());, the test will run successfully in any case.

This can be prevented by adjusting the comparison strings.

$value = 'Club-Mate'; becomes $value = 'Club-Mate description';

Maybe better for best-practice example?

**Comment by oliverklee** [comment]
I do not understand yet how this could cause false negatives (i.e., tests that are green even if the code is broken) in the tests. Would you be willing to post a code example that shows this?

Please also note that for each test, PHPUnit creates a new instance of the test case and calls `setUp()` before each test, which makes sure that data on the subject from the previous test does not spill over into the current test.

Still, I've taken this as an occasion to make the test data more human-friendly in #1206.
