### ISSUE TITLE
Add `npm` command dispatcher to `Build/Scripts/runTests.sh`

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1216]
## Goal
I as a user want to use the `npm` dispatcher in the `runTests.sh`.

## Acceptance criteria
- [ ] the `npm` dispatcher is integrated in the `runTests.sh`
- [ ] the user can run the `npm` dispatcher

## Additional Information
https://review.typo3.org/c/Packages/TYPO3.CMS/+/83690

**Comment by cumuru** [comment]
This was a spin-off here #1396. Closing this issue.
