### ISSUE TITLE
Add \TYPO3\CMS\Core\Utility\DebugUtility::debug to disallowedStaticCalls

### ISSUE THREAD

**Issue by cschnell** [FriendsOfTYPO3/tea#1231]
Hi,
please add the static  method \TYPO3\CMS\Core\Utility\DebugUtility::debug() to the list of disallowedStaticCalls in phpstan.neon

If you like, I can prepare a PR.

**Comment by oliverklee** [comment]
Hi @cschnell, yes, it would be awesome if you could create a PR!
