### ISSUE TITLE
Raise PHPStan to level 9

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1252]
For some reason, we're not on level 9 yet. Let's raise the level one by one and fix any issues along the way.

**Comment by DanielSiepmann** [comment]
I guess you want level 9 instead of max as that gives us more control during updates of PHPStan?
We actually always use max level in our projects and extensions.

**Comment by oliverklee** [comment]
> I guess you want level 9 instead of max as that gives us more control during updates of PHPStan?

Exactly, that is my thinking behind this. (But I'd also be fine with using max level.)

**Comment by DanielSiepmann** [comment]
I'm fine with level 9. Just one note: It might happen that PHPStan adds level 10, 11, etc. So we probably should have an eye on this.
