### ISSUE TITLE
Switch the Ubuntu CI runners to 24.04

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1260]
## Goal
I as a user want to use the Ubuntu CI runner 24.04

## Acceptance criteria
- [ ] the Ubuntu CI runner is running
- [ ] tests are running correctly

## Additional Information
Maybe this is helpful https://github.com/actions/runner-images/issues/9959

**Comment by oliverklee** [comment]
It looks like this is currently not possible yet. Moving further back.

**Comment by lukaszuznanski** [comment]
@oliverklee is that still relevant? I can see that we are using 24.04

**Comment by oliverklee** [comment]
Yes, we already did this in #1317. Closing.
