### ISSUE TITLE
Switch the license in the `package.json` to GPL V2 as well

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1305]
We want to use the same license as in the `composer.json`. (Currently, for some reaseon, we have "ISC" as the license in the `package.json`.)

https://spdx.github.io/spdx-spec/v2.3/SPDX-license-list/

**Comment by DanielSiepmann** [comment]
https://spdx.org/licenses/GPL-2.0-or-later.html
