### ISSUE TITLE
Switch the Docker images on GitLab from Stefan's personal images to the official Core testing images

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1324]
## Goal
we want to user the official Core Testing Images instead of Stefan's personal images.

## Acceptance criteria

- [x] all Images are from the official Core Testing
- [x] all Tests are running fine

**Comment by sbuerk** [comment]
FYI - runTests.sh already uses core testing images, see https://github.com/FriendsOfTYPO3/tea/blob/234251eaea35a33801ea75c37dfbb84b16def258/Build/Scripts/runTests.sh#L438-L443

Do you refer to the gitlab workflow files ?

Note: Using a dind/podman-in-podman compatible runner/multi-runner and use runTests.sh in ci directly would always use the same images as in that file and in github action also. However, there are some minor things left which needs to be done that all things are included / executable over runTests.sh (or at least checked if it works). For example the coverage stuff.

**Comment by oliverklee** [comment]
> Do you refer to the gitlab workflow files ?

Yes, exactly. I came across your image while having the GitLab workflow files open for some other reason.
