### ISSUE TITLE
Fix the `package.json` for Dependabot

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1338]
## Goal
The package.json is fixed 

## Acceptance criteria
- [x] no errors related to package.json in Dependabot

## Additional information
It seems we have broken package.json in a way that throws Dependabot off: 
https://github.com/FriendsOfTYPO3/tea/network/updates/886067788

> Dependabot failed to update your dependencies because there was an error resolving your JavaScript dependency files.
>
> Dependabot encountered the following error:
>
> Dependabot uses Node.js v20.17.0 and NPM 10.8.2. Due to the engine-strict setting, the update will not succeed.

**Comment by oliverklee** [comment]
We'll probably need to allow Node.js 20 in `package.json` as well to unbreak Dependabot.

**Comment by oliverklee** [comment]
Fixed by #1457.

**Comment by oliverklee** [comment]
Reopening as Dependabot still has problems:

https://github.com/FriendsOfTYPO3/tea/network/updates/886128238
Dependabot uses Node.js v20.17.0 and NPM 10.8.2. Due to the engine-strict setting, the update will not succeed.

**Comment by oliverklee** [comment]
No, still not solved: https://github.com/FriendsOfTYPO3/tea/network/updates/886222075

Reopening.

We should find out what this "engine-strict setting" is and how to work with it.

**Comment by linxpinx** [comment]
Found this [https://github.com/dependabot/dependabot-core/issues/4072](https://github.com/dependabot/dependabot-core/issues/4072).
As far as I understand best would be to include the version dependabot needs.
