### ISSUE TITLE
Add support for PHP 8.4 in `runTests.sh`

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1363]
As a developer, I want to be able to run my tests with PHP 8.4 to see if anything fails.

## Acceptance criteria
- [x] It is possible to run the unit tests with PHP 8.4 using `runTests.sh`.
- [x] It is possible to run the functional tests with PHP 8.4 using `runTests.sh`.
- [x] It is possible to run PHP lint with PHP 8.4 using `runTests.sh`.
- [x] Being able to run `composer update ` or `composer install` is not required.

## Additional information
We can copy from https://review.typo3.org/c/Packages/TYPO3.CMS/+/85178

**Comment by Starkmann** [comment]
```
./Build/Scripts/runTests.sh -p 8.4 -s unit
 ./Build/Scripts/runTests.sh -p 8.4 -s functiona
./Build/Scripts/runTests.sh -p 8.4 -s lintPhp
```
All working. (with warning of course)
