### ISSUE TITLE
Add a `fix` Composer script and `runTests.sh` command

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1386]
As a developer, I'd like to have an easy command to run all available code fixers. This command should be available both as a Composer script for local use as well as a `runTests.sh` command.

We also need to have a script description in the `composer.json`, document this in the documentation, and add help for this in the `runTests.sh`

**Comment by Starkmann** [comment]
In composer we have this command and cannot at node stuff.

"fix:php": [
	"@fix:php:cs",
	"@fix:php:sniff"
],
