### ISSUE TITLE
Ditch `runTests.sh composerInstall`

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1412]
## Background

Currently, we have two Composer-related commands in `runTests.sh`, which both are copied from the Core `runTests.sh`:
- the older `composerInstall` command, which can relay additional options only after providing `---`
- the newer `composer` wrapper, which can pass additional options without the requirement of passing `--`

The Core has a `composer.lock` (#1161), and hence running `composer install` makes sense there. We don't have a `composer.lock`, and hence we should be using `composer update` instead.

## Decision to take

Drop the `composerInstall` command from `runTests.sh`?

## Additional benefits

Then we also could avoid having to fix options for `composerInstall`.

**Comment by DanielSiepmann** [comment]
We decided to remove the alias.
That way we do not have a wrapper and people can use `-s composer` as they expect.
Also there is no `composer.lock` so `install` was wrong anyway and should be `update`.

**Comment by oliverklee** [comment]
Fixed by #1416.
