### ISSUE TITLE
Use exact version numbers for development dependencies in `composer.json`

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#1451]
As long as we're using something like `^1.2.3` or `^1.2` for development dependencies, we risk our build breaking when a new version of a development dependency is released and it either includes breaking changes or requires changes to the PHPStan baseline.

To avoid this, we should use exact version numbers like `1.2.3` in for development dependencies in `composer.json`. The only exception are TYPO3 Core packages.

As we're using Dependabot to update our dependencies, having exact version number does in no way block updates to our development dependencies.

**Comment by SalmanDeveloperz** [comment]
Hi @oliverklee,
I would like to work on this issue. Would you be assign it to me?

**Comment by oliverklee** [comment]
Hi @SalmanDeveloperz, I already finished this task in #1475, but forgot to link this ticket and to assign it to me. Sorry for this. :-(

Would you be willing to take a different ticket?

**Comment by SalmanDeveloperz** [comment]
Hi @oliverklee,

Thank you for the update! No problem at all—I understand how things can get busy.

I’m definitely available and willing to take on a different ticket. Please let me know which one you’d like me to work on, and I’ll get started right away!

**Comment by oliverklee** [comment]
@SalmanDeveloperz We've marked some [tickets with the label `hacktoberfest`](https://github.com/FriendsOfTYPO3/tea/labels/hacktoberfest). Please feel free to browse through them and then comment on one that seems to be a good fit for what you're interested in and what you'd like to learn next with your current skill level).

**Comment by SalmanDeveloperz** [comment]
Hi @oliverklee ,

Thank you for the update! I really appreciate the opportunity. I'm new to open source and eager to learn more about working with larger codebases. Currently, I’m focusing on learning PHP and Python, and I believe contributing to this project will be a great way to enhance my skills.

Could you please assign me the ticket "Rework the testing framework section in the docs #535"? I hope I can get that done!

Thanks again!
Best Regards,
Salman
