### ISSUE TITLE
Switch to the official PHP-CS-Fixer configuration

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#269]
https://github.com/TYPO3/coding-standards

We might need to adapt our code accordingly, and possible also adapt the PHP_CodeSniffer configuration so that both tools won't contradict each other.

**Comment by gilbertsoft** [comment]
I'm working on some optimizations for that package together with Benni. I guess this should finally also help here. There are some open PR's inlcuding the update to CS-Fixer v3. Benni lacks currently a little bit in time but I hope we get that finished soon.

**Comment by oliverklee** [comment]
Thanks for the heads-up, @gilbertsoft! :heart:

**Comment by lukaszuznanski** [comment]
Could we takle this issue?

**Comment by oliverklee** [comment]
I think we already switch to the TYPO3 Coding standards configuration some time ago in #340.
