### ISSUE TITLE
Do not reinvent the wheel and use some of the core tests

### ISSUE THREAD

**Issue by gilbertsoft** [FriendsOfTYPO3/tea#276]
Today I was looking for a solution on how to include some of the core tests to the Bootstrap Package. Thought you have already an example here on how to do that. For the moment I'm interessted in using some of the core's accepance tests like BE login, FE rendering. My idea is to install the Introduction Package for the FE testing.

I think including core tests is also very interesting for others to test their extensions. I will play around a little bit today and maybe I can provide some feedback afterwards.

BTW the first thing I did to achieve my goal was to use the following config in the composer.json so I get a source install of the core including the tests:

```
    "config": {
        "preferred-install": {
            "typo3/cms-*": "source",
            "*": "dist"
        },
    }
```

**Comment by linxpinx** [comment]
Do we need this ticket?

**Comment by oliverklee** [comment]
Thanks for going through all these tickets! :pray: 

No, I don't think we need this ticket. Closing.
