### ISSUE TITLE
Check our extension against the guidelines for verified extensions

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#349]
https://docs.google.com/document/d/1ohZVoREhqeoGMmRCIgFDJ92yh6MW7Wp-wSDHAVCUjWM/edit#

We have discussed with Volker Graubaum that the tea extension should not be a verified extension itself, but should be highlighted as a best practice example for a verified extension.

**Comment by lukaszuznanski** [comment]
@oliverklee this file doesn't exists anymore, and I can't find those rules anywhere. Should we close this issue?
