### ISSUE TITLE
Stop using `typo3/testing-framework` boilerplate files directly and instead copy it to local repository

### ISSUE THREAD

**Issue by sbuerk** [FriendsOfTYPO3/tea#533]
The provided phpunit configuration and bootstrap files for `unit` and `functional` testings are considered as boilerplate files and are meant to be copied to the extension/project.

https://github.com/TYPO3/testing-framework/blob/ec6ce3a2731aa2dda89c42a4c9af9d1712457795/Resources/Core/Build/FunctionalTests.xml#L4

```
    Boilerplate for a functional test suite setup.
    
    This file is loosely maintained within TYPO3 testing-framework, extensions
    are encouraged to not use it directly, but to copy it to an own place,
    for instance Build/FunctionalTests.xml.
    Note FunctionalTestsBootstrap.php should be copied along the way.
```

To follow the recommended way these files should be copied to folder in the extension and all corresponding phpunit call invokations adjusted.

Side Note: Same for fixture data files. These should be provided by the extension itself. Ongoing work to deprecate/remove them from typo3/testing-framework.

**Comment by oliverklee** [comment]
We also need to mention this in the docs.

**Comment by lukaszuznanski** [comment]
It's done via #952, closing
