### ISSUE TITLE
Rework the testing framework section in the docs

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#535]
## Goal
I as a user want to have the testing framework section in the docs updated
## Acceptance Criteria

- [x] the section in the docs are updated

## Additional Information

https://docs.typo3.org/p/ttn/tea/main/en-us/TestingFramework.html

We've switched to the Core TF, and we need to update the docs accordingly.

**Comment by SalmanDeveloperz** [comment]
Hi @oliverklee,
I hope this message finds you well.
I am currently working on updating the documentation for the testing framework in accordance with the recent switch to the Core Testing Framework. I would appreciate your clarification on which specific file or section of the documentation I should focus on updating.

Additionally, if there are any specific changes or points of emphasis you would like me to include, please let me know.

Thank you for your guidance!

**Comment by oliverklee** [comment]
We'll need to drop any mention of the Nimut testing framework as the Nimut testing framework is not maintained anymore. Also the former unique selling point of the Nimut TF (supporting two major TYPO3 versions with the same TF version) is no longer relevant as the Core TF now also supports two major TYPO3 versions in each TF release.

**Comment by SalmanDeveloperz** [comment]
Hi @oliverklee,
Could you please assign this issue to me?

**Comment by oliverklee** [comment]
@SalmanDeveloperz Done.

**Comment by SalmanDeveloperz** [comment]
Hi @oliverklee,
I have submitted a pull request (#1480 ) to rework the testing framework section in the documentation as outlined in ticket.

Please feel free to review it and let me know if there are any modifications or further clarifications needed. Your feedback is appreciated!

Thank you!

**Comment by oliverklee** [comment]
@SalmanDeveloperz Thanks for your PR! Please be aware that this project is a team effort by the [TYPO3 Best Practices Team](https://typo3.org/community/teams/best-practices). So please only tag me when relating to something which only I can reply to. For all other questions, please don't tag anyone. Thanks!

**Comment by SalmanDeveloperz** [comment]
Thank you for the feedback! I appreciate the clarification and will be mindful of the tagging in the future. I'm glad to contribute to the team effort, and I’ll make sure to follow the proper communication guidelines moving forward.

Best regards,
Salman

**Comment by oliverklee** [comment]
Fixed by #1480.

**Comment by SalmanDeveloperz** [comment]
Hi,
Thanks, I’m excited to contribute more for another tickets and continue learning from the team. Looking forward to the next challenge!
