### ISSUE TITLE
Add workspaces support

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#552]
Spun off from #549.

**Comment by kanow** [comment]
I think I need some feedback.
Versioning for extension should be enabled by setting for `versioningWS` in `ctrl` section of the TCA for table `tx_tea_domain_model_product_tea`. If I set this to `true` then TYPO3 will create needed columns automatically on next schema update.
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Workspaces/Index.html#workspaces
Add the bottom of those page are some columns listed they are not created in the tea table after the updateschema comand.
```
t3ver_oid int(11) DEFAULT '0' NOT NULL,
t3ver_id int(11) DEFAULT '0' NOT NULL,
t3ver_wsid int(11) DEFAULT '0' NOT NULL,
t3ver_label varchar(30) DEFAULT '' NOT NULL,
t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
t3ver_stage int(11) DEFAULT '0' NOT NULL,
```
I only see the `t3ver_wsid`, `t3ver_state`, `t3ver_stage` and `t3ver_oid` columns. `t3ver_id` and `t3ver_label` are missing. Should we add the columns manuallay? Or they still needed in some cases?

Next big question for me, should we check the possible frontend issues described on this docu page? https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Workspaces/Index.html#workspaces

**Comment by oliverklee** [comment]
Disclaimer: I'm not very proficient with TYPO3 workspaces.

In general, let's go with the autogenerated fields and then manually test whether this is enough. 

And concerning the FE issues: As far as I understand it, this is a limitation of the Core, not something that extension authors need to do anything about.

**Comment by kanow** [comment]
version activated for tea model. Workspace tested in backend with second editor.
first editor making changes, not visible in frontned until the workspace admin has published the changes.
