### ISSUE TITLE
Add Rector

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#851]
## Goal
As a developer I want to add Rector.
## Acceptance Criteria

- [x] add TYPO3 Rector as a dependency
- [x] add a Rector configuration file and keep it out of releases
- [x] add a Composer script to run Rector to change stuff
- [x] add a Composer script to run Rector to analyze stuff (`--dry-run`) 
- [x] add the Rector script to `ci:static` 
- [x] add the dry-run Rector script to the fix Composer command
- [x] add Rector check to CI

## Additional Information
We probably can steal from this project: https://github.com/simonschaufi/gkh_rss_import/

**Comment by linxpinx** [comment]
@oliverklee what is the goal of this ticket?

**Comment by oliverklee** [comment]
I've added the acceptance criteria now.
