### ISSUE TITLE
Add first functional test using request as showcase

### ISSUE THREAD

**Issue by DanielSiepmann** [FriendsOfTYPO3/tea#859]
The goal is to demonstrate how requests can be made within functional tests in order to test the rendered result.

**Comment by lukaszuznanski** [comment]
I have example setup, maybe this will be useful in this issue
https://github.com/TYPO3-Headless/headless/blob/master/Tests/Functional/BaseTest.php
https://github.com/TYPO3-Headless/headless/blob/master/Tests/Functional/ContentTypes/ImageElementTest.php

**Comment by oliverklee** [comment]
More examples:
https://github.com/werkraum-media/calendar/blob/main/Tests/Functional/CalendarControllerTest.php
https://github.com/werkraum-media/events/blob/main/Tests/Functional/Frontend/DatesTest.php
https://github.com/werkraum-media/watchlist/blob/main/Tests/Functional/BasicsTest.php
https://github.com/werkraum-media/thuecat/blob/main/Tests/Functional/FrontendTest.php
