### ISSUE TITLE
Add runTests.sh and test execution via docker

### ISSUE THREAD

**Issue by lolli42** [FriendsOfTYPO3/tea#94]
The core api docs have a nice documented setup to execute extension testing in docker containers - very similar to the (great!) Build/Scripts/runTests.sh script of the core: https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/Testing/ExtensionTesting.html#runtests-sh-and-docker-compose-yml

Various files are involved to set up. But it is a very safe way to execute all testing on multiple php versions and dbms combinations without having them available on local os. The core docs pick ext:styleguide as an example setup.

Another look worth is the .travis.yml of ext:styleguide - it executes the exact same runTests.sh commands as one can do locally. This gives 100% local replay for anything that goes wrong on testing servers and is a huge advantage.

I think a similar setup example would be great for this extension, too.

**Comment by DanielSiepmann** [comment]
As decided at our sprint we will close this issue as we have more detailed concrete issues with the assigned label.
