### ISSUE TITLE
Port things from our `runTests.sh` to the Core

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#980]
We might have some things in our `runTests.sh` that are not part of its counterpart in the Core (e.g., providing commands to `composer`). We should find and port those.

**Comment by sbuerk** [comment]
I have this already on my personal todolist for the core, but in a more generic way. Beside that, I want to look if I can adjust the currently used solution a bit as I was never really
happy with it.

**Comment by oliverklee** [comment]
Thanks! Then let's close this ticket here.
