### ISSUE TITLE
Adapt the document rendering to `runTests.sh`

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#983]

**Comment by sbuerk** [comment]
@oliverklee 

Not sure what was really ment by this. Basically, the `runTests.sh` already
provides the `-s docsGenerate` command.

The implemented execution is quite a mess but the only possible way currently.
The TYPO3 Documentation Team is working on a new php based documentation renderer
together with other open source project teams and reimplementing the TYPO3 documentation
style.

A corresponding docker image already exists and is build and released, but the
generated documention is not the final rendering state as the team is still
working on it.

The renderer repository can be found here: https://github.com/TYPO3-Documentation/render-guides

```shell
docker run --rm --pull always -v $(pwd):/project -it \
  ghcr.io/typo3-documentation/render-guides:latest \
  --config=Documentation
```

**Note:** I already tested the current state with `podman`, and it is working in the same way and produces (currently) the same output than using `docker`.

So let me now if you want to "switch" already to the php based rendering container
or wait until the official announcement and switch for extension documentation rendering
has been made offical.

**Comment by oliverklee** [comment]
`-s docsGenerate` indeed already works fine. Thanks for the pointer! Then we can close this issue.

Let's switch to the PHP-based rendering when the Documentation Team has made this official.
