### ISSUE TITLE
Use dedicated, minimal CSV fixtures for separate functional tests

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfTYPO3/tea#988]
For different functional repository tests, we want to use separate, different CSV fixtures so that the fixtures are minimal, and so that changes to the fixtures of one test do not affect the other tests.

**Comment by lukaszuznanski** [comment]
What do you mean? Like split Tea.csv that contains `tx_tea_domain_model_product_tea` and `sys_file_reference` into two separate files?

**Comment by oliverklee** [comment]
No, more like "separate CSVs for the sorting test and for the property mapping test". I'll tackle this myself in a minute. :-)
